@startuml
'https://plantuml.com/class-diagram

class main{
HashMap<String, Integer> wordMap
String inputFile
findFrequency(wordMap, inputFile)
List<Map.Entry<String, Integer>> sortedList
sortMap(wordMap)
printList(sortedList)
}

class findFrequency{
Scanner scan
while(scan.hasNext())
return wordMap
}

class sortMap{
List<Map.Entry<String, Integer>> mapToList
Collections.sort()
return mapToList
}

class printList{
for(Map.Entry<String, Integer> word : sortedList)
word.getKey()
}

findFrequency *-- main
sortMap *-- main
printList *-- main

@enduml